VIA_ENABLE = no

QMK_SETTINGS = no

# Those two do not compile
TAP_DANCE_ENABLE = no
COMBO_ENABLE = no

KEY_OVERRIDE_ENABLE = yes
CAP_WORD_ENABLE = yes

# Size optimization
LADDER_ENABLE = no
MOUSEKEY_ENABLE = no
#COSOLE_ENABLE = no
#COMMAND_ENABLE = no
LTO_ENABLE = yes
KEY_LOCK_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
AVR_USE_MINIMAL_PRINTF = yes
